---
title: "NYC Restaurant Inspections Dashboard"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
---


```{r setup, include=FALSE}
#install.packages("devtools")
devtools::install_github("p8105/p8105.datasets")

library(flexdashboard)
library(p8105.datasets)
library(dplyr)
library(plotly)

data(rest_inspec)
nyc_restaurants <- rest_inspec

nyc_restaurants <- 
  nyc_restaurants |>
  filter(!is.na(score)) |>
  sample_n(5000)
```
### Inspection scores over time

```{r}
nyc_restaurants |>
  plot_ly(x = ~inspection_date, y = ~score, type = 'scatter', mode = 'markers', 
          color = ~score) |>
  layout(title = "Inspection scores over time", 
         xaxis = list(title = "Inspection date"), 
         yaxis = list(title = "Score"))
```

### Score distribution by cuisine

```{r}
nyc_restaurants |>
  plot_ly(y = ~score, x = ~cuisine_description, type = 'box', color = ~cuisine_description) |>
  layout(title = "Score distribution by cuisine",
         xaxis = list(title = "Cuisine type", tickangle = -45),
         yaxis = list(title = "Score"))
```

### Number of restaurants per borough

```{r}
nyc_restaurants |>
  count(boro) |>
  plot_ly(x = ~boro, y = ~n, type = 'bar', color = ~boro) |>
  layout(title = "Number of restaurants per borough",
         xaxis = list(title = "Borough"),
         yaxis = list(title = "Count"))
```



















